export type ApiErrorCode =
  | 'VALIDATION_ERROR'
  | 'CSRF_FAILED'
  | 'ACCOUNT_UNAVAILABLE'
  | 'ACTIVATION_FAILED'
  | 'LOGIN_FAILED'
  | 'TENURE_ELIGIBILITY_REQUIRED'
  | 'INVALID_PHOTO'
  | 'PHOTO_STORAGE_UNAVAILABLE'
  | 'REQUEST_PENDING'
  | 'REVISION_CONFLICT'
  | 'PROFILE_CHANGED'
  | 'TRAINING_VERIFICATION_POLICY_REQUIRED'
  | 'EXPLICIT_CANONICAL_WORKFLOW_REQUIRED'
  | 'SCHEDULE_CHANGED'
  | 'UNAUTHENTICATED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'RATE_LIMITED'
  | 'WEEKLY_SCHEDULE_ALREADY_EXISTS'
  | 'TEACHER_CURRENT_INSTITUTION_REQUIRED'
  | 'WEEKLY_SCHEDULE_REVISION_CONFLICT'
  | 'WEEKLY_SCHEDULE_SLOT_OVERLAP'
  | 'TEACHER_INACTIVE'
  | 'VISIT_WORKPLACE_UNAVAILABLE'
  | 'VISIT_WORKPLACE_CHANGED'
  | 'VISIT_SCHEDULE_CONTEXT_CHANGED'
  | 'VISIT_WEEKLY_SCHEDULE_MISSING'
  | 'VISIT_OUTSIDE_WEEKLY_SCHEDULE'
  | 'VISIT_OVERLAP_CONFLICT'
  | 'VISIT_REVISION_CONFLICT'
  | 'VISIT_STATE_CONFLICT'
  | 'VISIT_TYPE_LOCKED'
  | 'REPORT_TYPE_CONFLICT'
  | 'REPORT_STATE_CONFLICT'
  | 'REPORT_REVISION_CONFLICT'
  | 'FOLLOW_UP_REPORT_NOT_READY'
  | 'FOLLOW_UP_STATE_CONFLICT'
  | 'FOLLOW_UP_REVISION_CONFLICT'
  | 'INSPECTOR_PROFESSIONAL_IDENTITY_REQUIRED'
  | 'INTERNAL_ERROR';

export type ApiFieldErrors = Record<string, string[]>;

export class ApiError extends Error {
  constructor(
    readonly status: number,
    readonly code: ApiErrorCode,
    message: string,
    readonly fields?: ApiFieldErrors,
  ) {
    super(message);
    this.name = 'ApiError';
  }
}
