import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import { Button, Card, CardContent, EmptyState, ErrorState, LoadingState, StatusBadge } from '../ui';
import { portalFetch, requestLabels, stateLabels, trainingLabels } from './client';
type History = { requests: Array<{ id: string; kind: string; status: string; updatedAt: string }>; corrections: Array<{ id: string; academicYear: string; status: string }>; events: Array<{ id: string; action: string; occurredAt: string }>; visits: Array<{ id: string; status: string; institutionNameSnapshot: string; report: { id: string; status: string; _count: { followUps: number } } | null }> };
const eventLabels: Record<string, string> = { TEACHER_PROFILE_UPDATED: 'تحديث البيانات المعتمدة', TEACHER_REQUEST_CREATED: 'تصريح جديد من الأستاذ', TEACHER_REQUEST_DECIDED: 'قرار مراجعة تصريح', TEACHER_INVITATION_ISSUED: 'إصدار دعوة الحساب', TEACHER_ACCOUNT_ACTIVATED: 'تفعيل حساب الأستاذ', TEACHER_SCHEDULE_CORRECTION_REQUESTED: 'طلب تصحيح التوزيع', TEACHER_SCHEDULE_CORRECTION_SUBMITTED: 'إعادة إرسال التصحيح', TEACHER_SCHEDULE_CORRECTION_ACCEPTED: 'اعتماد التصحيح', TEACHER_INSTITUTION_LINKED: 'اعتماد المؤسسة الأصلية', TEACHER_INSTITUTION_CHANGED: 'تغيير المؤسسة الأصلية' };
export function DossierUpdates({ teacherId, trainingStatus, verifiedAt }: { teacherId: string; trainingStatus?: string | null; verifiedAt?: string | null }) {
  const [history, setHistory] = useState<History | null>(null); const [failed, setFailed] = useState(false); const [retry, setRetry] = useState(0);
  useEffect(() => { let active = true; setHistory(null); setFailed(false); void portalFetch<{ data: History }>(`/teachers/${teacherId}/evolution-history`).then((r) => { if (active) setHistory(r.data); }).catch(() => { if (active) setFailed(true); }); return () => { active = false; }; }, [teacherId, retry]);
  return <Card><CardContent><h2>التكوين والتحديثات المهنية</h2><p>التكوين المعتمد: {trainingLabels[trainingStatus ?? ''] ?? 'غير محدد'} · {verifiedAt ? 'إتمام موثق' : 'لا يوجد إثبات إتمام معتمد'}</p><Link to={`/app/teacher-requests?teacherId=${teacherId}`}>مراجعة تحديثات هذا الأستاذ</Link>
    {failed ? <ErrorState compact title="تعذر تحميل سجل التحديثات" action={<Button variant="secondary" onClick={() => setRetry((n) => n + 1)}>إعادة تحميل السجل</Button>} /> : !history ? <LoadingState compact /> : <>
      {history.requests.length ? <ul>{history.requests.map((r) => <li key={r.id}>{requestLabels[r.kind]} <StatusBadge>{stateLabels[r.status]}</StatusBadge></li>)}</ul> : <EmptyState compact title="لا توجد تصريحات حساب مسجلة" />}
      {history.corrections.map((c) => <p key={c.id}><Link to={`/app/teachers/${teacherId}/schedules?academicYear=${c.academicYear}`}>{stateLabels[c.status]} — <bdi>{c.academicYear}</bdi></Link></p>)}
      <h3>أحدث الزيارات والتقارير والمتابعات — في نطاق ملكيتك</h3>{history.visits?.length ? <ul>{history.visits.map((v) => <li key={v.id}><Link to={`/app/visits/${v.id}`}>زيارة <bdi>{v.institutionNameSnapshot}</bdi></Link> — {({ PLANNED: 'مبرمجة', COMPLETED: 'مكتملة', CANCELLED: 'ملغاة' } as Record<string, string>)[v.status] ?? 'سجل زيارة'}{v.report ? <p><Link to={`/app/visits/${v.id}/report`}>التقرير {v.report.status === 'FINAL' ? 'النهائي' : 'المسودة'} والمتابعات ({v.report._count.followUps})</Link></p> : null}</li>)}</ul> : <p>لا توجد زيارات حديثة ضمن صلاحياتك؛ يبقى تاريخ الزيارات في مساحته.</p>}
      <details><summary>سجل الإجراءات — أحدث 25 إجراءً مرتبطًا</summary><ol>{history.events.map((e) => <li key={e.id}>{eventLabels[e.action] ?? 'إجراء مهني مسجل'} — <time dateTime={e.occurredAt}>{new Date(e.occurredAt).toLocaleString('ar-DZ', { timeZone: 'Africa/Algiers' })}</time></li>)}</ol><p>هذا ملخص حديث، وليس بديلًا عن تاريخ الزيارات والتقارير أو سجل التدقيق الكامل.</p></details>
    </>}
  </CardContent></Card>;
}
