import { useEffect, useRef, useState, type FormEvent } from 'react';
import { useParams, useSearchParams } from 'react-router';
import { getTeacherProfile, getValidWorkplaces, getWeeklySchedule, type ValidWorkplaceOption, type WeeklySchedule, type WeeklyScheduleSlotInput } from '../auth/client';
import { Button, Dialog, EmptyState, ErrorState, Input, PageHeader, SuccessState } from '../ui';
import { portalFetch, stateLabels, type ScheduleReview } from './client';
import { WeekBoard } from './TeacherScheduleEditor';
export function InspectorSchedulePage() {
  const { id = '' } = useParams(); const [query] = useSearchParams(); const [year, setYear] = useState(query.get('academicYear') ?? ''); const [schedule, setSchedule] = useState<WeeklySchedule | null>(null); const [corrections, setCorrections] = useState<ScheduleReview[]>([]);
  const [confirmation, setConfirmation] = useState<{ review: ScheduleReview; decision: 'accept' | 'reject' } | null>(null);
  const [reason, setReason] = useState(''); const [teacherName, setTeacherName] = useState('');
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [note, setNote] = useState(''); const [loadedYear, setLoadedYear] = useState(''); const [success, setSuccess] = useState('');
  const [places, setPlaces] = useState<ValidWorkplaceOption[]>([]); const epoch = useRef(0);
  useEffect(() => { epoch.current += 1; setLoadedYear(''); setSchedule(null); setCorrections([]); setConfirmation(null); return () => { epoch.current += 1; }; }, [id]);
  async function load(event?: FormEvent) { event?.preventDefault(); const current = ++epoch.current; const requestedYear = year; setLoadedYear(''); setError(''); setSaving(true); try { const [result, updates, workplaces, profile] = await Promise.all([getWeeklySchedule(id, requestedYear), portalFetch<{ data: ScheduleReview[] }>(`/teachers/${id}/schedule-corrections`), getValidWorkplaces(id, { date: new Intl.DateTimeFormat('en-CA', { timeZone: 'Africa/Algiers' }).format(new Date()) }), getTeacherProfile(id)]); if (epoch.current !== current) return; setTeacherName(`${profile.data.name} ${profile.data.surname}`); setPlaces(workplaces.data.items); setSchedule(result.data.schedule); setCorrections(updates.data.filter((c) => c.academicYear === requestedYear)); setLoadedYear(requestedYear); } catch { if (epoch.current === current) setError('تعذر عرض التوزيع. تحقق من السنة والصلاحيات.'); } finally { if (epoch.current === current) setSaving(false); } }
  async function mutate(path: string, payload: unknown) { setSaving(true); setError(''); try { await portalFetch(path, payload, { inspector: true }); setNote(''); await load(); setConfirmation(null); setSuccess('تم تسجيل الإجراء.'); } catch (e) { setError(e instanceof Error ? e.message : 'تعذر تسجيل الإجراء.'); } finally { setSaving(false); } }
  return <section dir="rtl"><PageHeader variant="compact" title="التوزيع الأسبوعي — إشراف وتصحيح" breadcrumbs={[{ label: 'ملف الأستاذ', to: `/app/teachers/${id}` }, { label: 'التوزيع الأسبوعي' }]} />
    <form onSubmit={(e) => { void load(e); }}><Input id="inspector-schedule-year" label="السنة الدراسية" value={year} onChange={(e) => setYear(e.target.value)} required /><Button type="submit" loading={saving}>عرض التوزيع</Button></form>
    {error ? <ErrorState compact title={error} /> : null}{success ? <SuccessState title={success} /> : null}
    {loadedYear ? schedule ? <><p><bdi>{teacherName}</bdi> — <bdi>{loadedYear}</bdi></p><h2>الجدول الساري</h2><WeekBoard slots={schedule.slots as unknown as WeeklyScheduleSlotInput[]} places={[]} />
      {!corrections.some((c) => c.status === 'REQUESTED' || c.status === 'SUBMITTED') ? <form onSubmit={(e) => { e.preventDefault(); void mutate(`/teachers/${id}/schedule-corrections`, { academicYear: loadedYear, note, expectedRevision: schedule.revision }); }}><Input id="schedule-correction-note" label="التصحيح المطلوب من الأستاذ" required maxLength={500} value={note} onChange={(e) => setNote(e.target.value)} /><Button type="submit" loading={saving}>طلب تصحيح</Button></form> : null}
      {corrections.map((c) => <section key={c.id} aria-label="مراجعة مقترح الجدول"><h2>{stateLabels[c.status]} — {c.origin === 'TEACHER_UPDATE' ? 'تحديث مستقل من الأستاذ' : 'تصحيح بطلب المفتش'}</h2><p><bdi>{c.note}</bdi></p>{c.decisionNote ? <p>سبب الرفض: <bdi>{c.decisionNote}</bdi></p> : null}{c.proposedSlots ? <><h3>النسخة المقترحة</h3><WeekBoard slots={c.proposedSlots} places={[...places, ...schedule.slots.flatMap((s) => s.institution ? [{ id: s.institution.id, name: s.institution.name }] : [])]} /></> : null}{c.status === 'SUBMITTED' ? <div className="portal-actions"><Button onClick={() => { setError(''); setReason(''); setConfirmation({ review: c, decision: 'accept' }); }} loading={saving}>{c.origin === 'TEACHER_UPDATE' ? 'اعتماد التحديث' : 'اعتماد التصحيح'}</Button><Button variant="secondary" onClick={() => { setError(''); setReason(''); setConfirmation({ review: c, decision: 'reject' }); }} disabled={saving}>رفض المقترح</Button></div> : null}</section>)}
    </> : <EmptyState compact title="لم يرسل الأستاذ توزيعًا لهذه السنة" description="الأستاذ يدخل الجدول من مساحته؛ المفتش يراجعه ويطلب التصحيح." /> : null}
    <Dialog open={Boolean(confirmation)} title={confirmation?.decision === 'reject' ? 'رفض مقترح الجدول' : 'اعتماد مقترح الجدول'} onClose={() => { if (!saving) setConfirmation(null); }} actions={<><Button loading={saving} disabled={confirmation?.decision === 'reject' && !reason.trim()} onClick={() => { if (confirmation) void mutate(`/schedule-corrections/${confirmation.review.id}/${confirmation.decision}`, { expectedRevision: confirmation.review.revision, ...(confirmation.decision === 'reject' ? { reason } : {}) }); }}>{confirmation?.decision === 'reject' ? 'تأكيد رفض المقترح' : confirmation?.review.origin === 'TEACHER_UPDATE' ? 'تأكيد اعتماد التحديث' : 'تأكيد اعتماد التصحيح'}</Button><Button variant="secondary" disabled={saving} onClick={() => setConfirmation(null)}>إلغاء</Button></>}>
      {confirmation?.decision === 'reject' ? <><p>يبقى الجدول الساري دون تغيير. يُحفظ المقترح وسبب رفضه ويستطيع الأستاذ إرسال نسخة جديدة.</p><Input id="schedule-rejection-reason" label="سبب رفض المقترح" required maxLength={500} value={reason} onChange={(e) => setReason(e.target.value)} /></> : <p>سيستبدل الجدول الساري بعد التحقق، وتُحفظ نسخته السابقة دون تغيير تاريخ الزيارات والتقارير.</p>}{error ? <p role="alert">{error}</p> : null}</Dialog>
  </section>;
}
