import { PrismaClient } from '@prisma/client';
import { createApp } from './app.js';
import { registerAuthRoutes } from './identity/auth-routes.js';
import { requireAuthenticatedInspector } from './identity/auth-routes.js';
import { registerInstitutionRoutes } from './institutions/routes.js';
import { registerDistrictContextRoute } from './identity/district-routes.js';
import { registerProfessionalIdentityRoutes } from './identity/professional-identity-routes.js';
import { registerTeacherSubmissionRoutes } from './intake/routes.js';
import { registerInspectorSubmissionRoutes } from './intake/inspector-routes.js';
import { registerSubmissionDecisionRoute } from './intake/decision-routes.js';
import { registerTeacherProfileRoutes } from './teachers/routes.js';
import { registerTeacherQualificationRoutes } from './teachers/qualification-routes.js';
import { registerTeacherSupplementaryWorkplaceRoutes } from './teachers/supplementary-workplace-routes.js';
import { registerTeacherDirectoryRoutes } from './teachers/directory-routes.js';
import { registerWeeklyScheduleRoutes } from './schedules/routes.js';
import { registerPedagogicalVisitRoutes } from './visits/routes.js';
import { registerInspectionReportRoutes } from './reports/routes.js';
import { registerFollowUpRoutes } from './followups/routes.js';

const port = Number(process.env.PORT ?? 3001);
const prisma = new PrismaClient();

createApp((app) => {
  registerAuthRoutes(app, prisma);
  const requireInspector = requireAuthenticatedInspector(prisma);
  registerDistrictContextRoute(app, prisma, requireInspector);
  registerProfessionalIdentityRoutes(app, prisma, requireInspector);
  registerInstitutionRoutes(app, prisma, requireInspector);
  registerTeacherSubmissionRoutes(app, prisma);
  registerInspectorSubmissionRoutes(app, prisma, requireInspector);
  registerSubmissionDecisionRoute(app, prisma, requireInspector);
  registerTeacherDirectoryRoutes(app, prisma, requireInspector);
  registerTeacherProfileRoutes(app, prisma, requireInspector);
  registerTeacherQualificationRoutes(app, prisma, requireInspector);
  registerTeacherSupplementaryWorkplaceRoutes(app, prisma, requireInspector);
  registerWeeklyScheduleRoutes(app, prisma, requireInspector);
  registerPedagogicalVisitRoutes(app, prisma, requireInspector);
  registerInspectionReportRoutes(app, prisma, requireInspector);
  registerFollowUpRoutes(app, prisma, requireInspector);
}).listen(port);
